server:
  servlet:
    context-path: /EqPancreditDeveloperTest
  port: 18080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

data:
  file-path: /tmp/data.json # Absolute path to the data file
